const arabicWords = [
  "بَيْتٌ",
  "مَسْجِدٌ",
  "بَابٌ",
  "كِتَابٌ",
  "قَلَمٌ",
  "مِفْتَاحٌ",
  "مَكْتَبٌ",
  "سَرِيرٌ",
  "كُرْسِيٌّ",
  "نَجْمٌ",
  "قَمِيصٌ",
  "طَبِيبٌ",
  "إِمَامٌ",
  "حَجَرٌ",
  "لَبَنٌ",
  "سُكَّرٌ",
  "مِنْدِيلٌ",
  "مُعَلِّمٌ",
  "دِيكٌ",
  "جَمَلٌ",
  "نَاقَةٌ",
  "حِصَانٌ",
  "حِمَارٌ",
  "قِطٌّ",
  "كَلْبٌ",
  "تَاجِرٌ",
  "رَجُلٌ",
  "طَالِبٌ",
  "وَلَدٌ",
  "غَنِيٌّ",
  "طَوِيلٌ",
  "بَارِدٌ",
  "جَالِسٌ",
  "جَدِيدٌ",
  "قَرِيبٌ",
  "نَظِيفٌ",
  "صَغِيرٌ",
  "خَفِيفٌ",
  "وَرَقَةٌ",
  "تُفَّاحَةٌ",
  "دُكَّانٌ",
  "مَرِيضٌ",
  "فَقِيرٌ",
  "قَصِيرٌ",
  "حَارٌّ",
  "وَاقِفٌ",
  "قَدِيمٌ",
  "بَعِيدٌ",
  "وَسِخٌ",
  "كَبِيرٌ",
  "ثَقِيلٌ",

  "أَيْنَ؟",
  "غُرْفَةٌ",
  "حَمَّامٌ",
  "مَطْبَخٌ",
  "فِي",
  "مِنْ",
  "إِلَى",
  "ٱلْيَابَانُ",
  "ٱلصِّينُ",
  "هِنْدُ",
  "مُدِيرٌ",
  "ٱلرَّسُولُ",
  "عَمٌّ",
  "شَارِعٌ",
  "خَالٌ",
  "مُغْلَقٌ",
  "ٱسْمٌ",
  "حَقِيبَةٌ",
  "تَحْتَ",
  "ٱبْنٌ",
  "سَيَّارَةٌ",
  "هُنَا",
  "هُنَاكَ",
  "بِنْتٌ",
  "طَبِيبٌ",
  "جَمَاعَةٌ",
  "مَكْسُورٌ",
  "شَجَرَةٌ",
  "ٱلْمَدْرَسَةُ ٱلثَّانَوِيَّةُ",
  "مُفَتِّشٌ",
  "فَتَاةٌ",
  "فَتًى",
  "دَفْتَرٌ",
  "مَلِيزِيَا",

  "أَبٌ",
  "آبَاءٌ",
  "ضَعِيفٌ",
  "ضِعَافٌ",
  "عَالِمٌ",
  "عُلَمَاءُ",
  "بَخِيلٌ",
  "ٱلسُّعُودِيَّةُ",
  "بَعْدَ",
  "قَوِيٌّ",
  "فَتًى",
  "فِتْيَةٌ",
  "طَوِيلٌ",
  "طَوِيلٌ",
  "طُلَّابٌ",
  "طَالِبٌ",
  "جَدِيدٌ",
  "جُدُدٌ",
  "ضَيْفٌ",
  "ضُيُوفٌ",
  "قَرْيَةٌ",
  "قُرًى",
  "ٱسْمٌ",
  "أَسْمَاءُ",
  "حَفِيدٌ",
  "مَطَارٌ",
  "كُلِّيَّةٌ",
  "كُلِّيَّةُ ٱلطِّبِّ",
  "كُلِّيَّةُ ٱلهَنْدَسَةِ",
  "كُلِّيَّةُ ٱلتِّجَارَةِ",
  "كُلِّيَّةُ ٱلشَّرِيعَةِ",
  "نَصْرَانِيٌّ",
  "نَصَارَى",
  "ٱلنَّبِيُّ",
  "الدِّينُ",
  "شَفَاهُ ٱللّٰهُ",
  "ٱلْقَاهِرَةُ",
  "ٱلْأُسْبُوعُ",
  "ٱلدَّرْسُ",
  "ٱلِٕخْتِبَارُ",
  "أَخٌ",
  "إِخْوَةٌ",
  "ٱلْيُونَانُ",
  "بِنْتٌ",
  "حَفِيدٌ",
  "ٱلْمَحْكَمَةُ",
  "ٱلْقِبْلَةُ",
  "ٱلدُّسْتُورُ",
  "ٱلنَّهْرُ",
  "ٱلْبَحْرُ",
  "ٱلْفُنْدُقُ",
  "ٱلطَّائِرَةُ",
  "مُدِيرُ ٱلشَّرِكَةِ",
  "يَابَانِيَّةٌ",
  "ٱلشَّرِكَةُ",
  "رَخِيصٌ",
  "قَمِيصٌ",
  "قُمْصَانٌ",
  "سَبُّورَةٌ",
  "رِيَالٌ",
  "حَيٌّ",
  "رَكْعَةٌ",
  "كُلُّ",
  "كُلُّهُمْ",
  "كُلُّكُمْ",
  "كُلُّنَا",
  "بَلَدٌ",
  "مُخْتَلِفٌ",
  "حَافِلَةٌ",
  "مِنْهُمْ",
  "أُورُوبَّا",
  "يُوغُوسْلَافِيَا",
  "شُكْرًا",
  "ٱلْيَوْمُ",
  "أَيَّامٌ",
  "ٱلثَّمَنُ",
  "نِصْفٌ",
  "رَكَعَاتٌ",
  "عَجَلَةٌ",
  "ٱلْعِيدُ",
  "ٱلسَّنَةُ",
  "نَافِذَةٌ",
  "مِسْطَرَةٌ",
  "أَحْمَرَ",
  "أَزْرَقَ",
  "أَخْضَرَ",
  "أَسْوَدَ",
  "أَصْفَرَ",
  "أَبْيَضَ",
  "دَقِیقَةٌ",
  "دَقَائِقُ",
  "مَفَاتِيحُ",
  "قَالَ",
  "قَالَتْ",
  "قَدَامَى",
  "رُكَّابٌ",
  "رَاكِبٌ",
  "الفِنْجَانُ",
  "الفَنَاجِينُ",
  "مَنَادِيلُ",
];

const dutchWords = [
  "huis",
  "moskee",
  "deur",
  "boek",
  "pen",
  "sleutel",
  "bureau",
  "bed",
  "stoel",
  "ster",
  "blouse",
  "dokter",
  "leider",
  "steen",
  "melk",
  "suiker",
  "doekje/servetje",
  "leraar",
  "haan",
  "kameel (m)",
  "kameel (v)",
  "paard",
  "ezel",
  "kat",
  "hond",
  "handelaar",
  "man",
  "student",
  "jongen",
  "rijk",
  "lang",
  "koud",
  "zittend",
  "nieuw (ev)",
  "dichtbij",
  "schoon",
  "klein",
  "licht",
  "het blaadje",
  "de appel",
  "de winkel",
  "ziek",
  "arm",
  "kort",
  "warm",
  "staand",
  "oud (ev)",
  "ver",
  "vies",
  "groot",
  "zwaar",
  "waar?",
  "kamer",
  "douche",
  "de keuken",
  "in",
  "van",
  "tot",
  "Japan",
  "China",
  "India",
  "directeur",
  "de boodschapper",
  "oom (vaderskant)",
  "de straat",
  "oom (moederskant)",
  "gesloten",
  "naam",
  "tas/koffer",
  "onder",
  "zoon",
  "auto",
  "hier",
  "daar",
  "meisje",
  "dokter",
  "gemeenschap",
  "gebroken",
  "boom",
  "de middelbare school",
  "inspecteur",
  "jonge dame",
  "jonge man",
  "schrift",
  "Maleisië",
  "vader",
  "vaders",
  "zwak",
  "zwakken",
  "persoon van kennis",
  "personen van kennis",
  "gierig",
  "Saudi-Arabië",
  "na",
  "sterk",
  "jongeman",
  "jongemannen",
  "lang (ev)",
  "lang (mv)",
  "studenten",
  "student",
  "nieuw (ev)",
  "nieuw (mv)",
  "gast",
  "gasten",
  "dorp",
  "dorpen",
  "naam",
  "namen",
  "kleinkind",
  "de vliegveld",
  "de faculteit",
  "de faculteit van geneeskunde",
  "de faculteit van engineering",
  "de faculteit van handel",
  "de faculteit van de islamitische wetgeving",
  "christen",
  "christenen",
  "de profeet",
  "de religie",
  "moge Allah hem genezen",
  "Caïro",
  "de week",
  "de les",
  "de toets",
  "broer",
  "broers",
  "Griekenland",
  "Meisje",
  "kleinzoon",
  "de rechtbank",
  "de gebedsrichting",
  "de grondwet",
  "de rivier",
  "de zee",
  "het hotel",
  "het vliegtuig",
  "de directeur van het bedrijf",
  "Japans",
  "het bedrijf",
  "goedkoop",
  "bloes",
  "bloezen",
  "schrijfbord",
  "Riyaal",
  "wijk",
  "gebedseenheid",
  "elke",
  "elke van hun",
  "elke van jullie",
  "elke van ons",
  "land",
  "verschillend",
  "bus",
  "van hen",
  "Europa",
  "Joegoslavië",
  "bedankt",
  "de dag",
  "dagen",
  "prijs",
  "helft",
  "gebedseenheden",
  "wiel",
  "het feest",
  "het jaar",
  "raam",
  "liniaal",
  "Rood",
  "Blauw",
  "Groen",
  "Zwart",
  "Geel",
  "Wit",
  "minuut",
  "minuten",
  "sleutels",
  "hij zei",
  "zij zei",
  "oud (mv)",
  "passagiers",
  "passagier",
  "de kom",
  "de kommen",
  "servetten/doekjes",
];

function generateNum() {
  //generate a random number
  return (num = Math.floor(Math.random() * arabicWords.length));
}
let randIndex = generateNum(); // Generate a random index
let totalWords = dutchWords.length;

function playGame() {
  //Game will be called via a button in the HTML file
  let answer = "";
  for (let i = 0; i < totalWords; i++) {
    //Iterate as much as the array length
    answer = prompt(`Wat is de vertaling van '${arabicWords[randIndex]}'?`); //Question the user
    if (answer.toLowerCase() === dutchWords[randIndex].toLowerCase()) {
      //Check answer
      alert(`Correct!`);
    } else {
      alert(
        `Incorrect. De vertaling van '${arabicWords[randIndex]}' is '${dutchWords[randIndex]}'.`
      );
    }
    randIndex = generateNum(); //Generate another random number after each iteration
  }
}

console.log(arabicWords.length);
console.log(dutchWords.length);
