const arabicWords = [
  "بَيْتٌ",
  "مَسْجِدٌ",
  "بَابٌ",
  "كِتَابٌ",
  "قَلَمٌ",
  "مِفْتَاحٌ",
  "مَكْتَبٌ",
  "سَرِيرٌ",
  "كُرْسِيٌّ",
  "نَجْمٌ",
  "قَمِيصٌ",
  "طَبِيبٌ",
  "إِمَامٌ",
  "حَجَرٌ",
  "لَبَنٌ",
  "سُكَّرٌ",
  "مِنْدِيلٌ",
  "مُعَلِّمٌ",
  "دِيكٌ",
  "جَمَلٌ",
  "نَاقَةٌ",
  "حِصَانٌ",
  "حِمَارٌ",
  "قِطٌّ",
  "كَلْبٌ",
  "تَاجِرٌ",
  "رَجُلٌ",
  "وَلَدٌ",
  "غَنِيٌّ",
  "طَوِيلٌ",
  "بَارِدٌ",
  "جَالِسٌ",
  "جَدِيدٌ",
  "قَرِيبٌ",
  "نَظِيفٌ",
  "صَغِيرٌ",
  "خَفِيفٌ",
  "وَرَقَةٌ",
  "تُفَّاحَةٌ",
  "دُكَّانٌ",
  "مَرِيضٌ",
  "فَقِيرٌ",
  "قَصِيرٌ",
  "حَارٌّ",
  "وَاقِفٌ",
  "قَدِيمٌ",
  "بَعِيدٌ",
  "وَسِخٌ",
  "كَبِيرٌ",
  "ثَقِيلٌ",

  "أَيْنَ",
  "غُرْفَةٌ",
  "حَمَّامٌ",
  "مَطْبَخٌ",
  "فِي",
  "مِنْ",
  "إِلَى",
  "ٱلْيَابَانُ",
  "ٱلصِّينُ",
  "هِنْدُ",
  "مُدِيرٌ",
  "ٱلرَّسُولُ",
  "عَمٌّ",
  "شَارِعٌ",
  "خَالٌ",
  "مُغْلَقٌ",
  "ٱسْمٌ",
  "حَقِيبَةٌ",
  "تَحْتَ",
  "ٱبْنٌ",
  "سَيَّارَةٌ",
  "هُنَا",
  "هُنَاكَ",
  "بِنْتٌ",
  "جَمَاعَةٌ",
  "مَكْسُورٌ",
  "شَجَرَةٌ",
  "ٱلْمَدْرَسَةُ ٱلثَّانَوِيَّةُ",
  "مُفَتِّشٌ",
  "فَتَاةٌ",
  "فَتًى",
  "دَفْتَرٌ",
  "مَلِيزِيَا",

  "أَبٌ",
  "آبَاءٌ",
  "ضَعِيفٌ",
  "ضِعَافٌ",
  "عَالِمٌ",
  "عُلَمَاءُ",
  "بَخِيلٌ",
  "ٱلسُّعُودِيَّةُ",
  "بَعْدَ",
  "قَوِيٌّ",
  "فِتْيَةٌ",
  "طِوَالٌ",
  "طُلَّابٌ",
  "طَالِبٌ",
  "جَدِيدٌ",
  "جُدُدٌ",
  "ضَيْفٌ",
  "ضُيُوفٌ",
  "قَرْيَةٌ",
  "قُرًى",
  "ٱسْمٌ",
  "أَسْمَاءُ",
  "مَطَارٌ",
  "كُلِّيَّةٌ",
  "كُلِّيَّةُ ٱلطِّبِّ",
  "كُلِّيَّةُ ٱلهَنْدَسَةِ",
  "كُلِّيَّةُ ٱلتِّجَارَةِ",
  "كُلِّيَّةُ ٱلشَّرِيعَةِ",
  "نَصْرَانِيٌّ",
  "نَصَارَى",
  "ٱلنَّبِيُّ",
  "الدِّينُ",
  "شَفَاهُ ٱللّٰهُ",
  "ٱلْقَاهِرَةُ",
  "ٱلْأُسْبُوعُ",
  "ٱلدَّرْسُ",
  "ٱلِٕخْتِبَارُ",
  "أَخٌ",
  "إِخْوَةٌ",
  "ٱلْيُونَانُ",
  "بِنْتٌ",
  "حَفِيدٌ",
  "ٱلْمَحْكَمَةُ",
  "ٱلْقِبْلَةُ",
  "ٱلدُّسْتُورُ",
  "ٱلنَّهْرُ",
  "ٱلْبَحْرُ",
  "ٱلْفُنْدُقُ",
  "ٱلطَّائِرَةُ",
  "مُدِيرُ ٱلشَّرِكَةِ",
  "يَابَانِيَّةٌ",
  "ٱلشَّرِكَةُ",
  "رَخِيصٌ",
  "قُمْصَانٌ",
  "سَبُّورَةٌ",
  "رِيَالٌ",
  "حَيٌّ",
  "رَكْعَةٌ",
  "كُلُّ",
  "كُلُّهُمْ",
  "كُلُّكُمْ",
  "كُلُّنَا",
  "بَلَدٌ",
  "مُخْتَلِفٌ",
  "حَافِلَةٌ",
  "مِنْهُمْ",
  "أُورُوبَّا",
  "يُوغُوسْلَافِيَا",
  "شُكْرًا",
  "ٱلْيَوْمُ",
  "أَيَّامٌ",
  "ٱلثَّمَنُ",
  "نِصْفٌ",
  "رَكَعَاتٌ",
  "عَجَلَةٌ",
  "ٱلْعِيدُ",
  "ٱلسَّنَةُ",
  "نَافِذَةٌ",
  "مِسْطَرَةٌ",
  "أَحْمَرُ",
  "أَزْرَقُ",
  "أَخْضَرُ",
  "أَسْوَدُ",
  "أَصْفَرُ",
  "أَبْيَضُ",
  "دَقِیقَةٌ",
  "دَقَائِقُ",
  "مَفَاتِيحُ",
  "قَالَ",
  "قَالَتْ",
  "قَدَامَى",
  "رُكَّابٌ",
  "رَاكِبٌ",
  "الفِنْجَانُ",
  "الفَنَاجِينُ",
  "مَنَادِيلُ",
  "الفنادق",
];

const dutchWords = [
  "huis",
  "moskee",
  "deur",
  "boek",
  "pen",
  "sleutel",
  "bureau",
  "bed",
  "stoel",
  "ster",
  "blouse",
  "dokter",
  "leider",
  "steen",
  "melk",
  "suiker",
  "doekje",
  "leraar",
  "haan",
  "kameel (m)",
  "kameel (v)",
  "paard",
  "ezel",
  "kat",
  "hond",
  "handelaar",
  "man",
  "jongen",
  "rijk",
  "lang",
  "koud",
  "zittend",
  "nieuw (ev)",
  "dichtbij",
  "schoon",
  "klein",
  "licht",
  "blaadje",
  "appel",
  "winkel",
  "ziek",
  "arm",
  "kort",
  "warm",
  "staand",
  "oud (ev)",
  "ver",
  "vies",
  "groot",
  "zwaar",

  "waar",
  "kamer",
  "douche",
  "keuken",
  "in",
  "van",
  "tot",
  "Japan",
  "China",
  "India",
  "directeur",
  "de boodschapper",
  "oom (vaderskant)",
  "straat",
  "oom (moederskant)",
  "gesloten",
  "naam",
  "tas",
  "onder",
  "zoon",
  "auto",
  "hier",
  "daar",
  "meisje",
  "gemeenschap",
  "gebroken",
  "boom",
  "de middelbare school",
  "inspecteur",
  "jonge dame",
  "jonge man",
  "schrift",
  "Maleisië",

  "vader",
  "vaders",
  "zwak (ev)",
  "zwak (mv)",
  "geleerde",
  "geleerden",
  "gierig",
  "Saudi-Arabië",
  "na",
  "sterk",
  "jongemannen",
  "lang (mv)",
  "studenten",
  "student",
  "nieuw (ev)",
  "nieuw (mv)",
  "gast",
  "gasten",
  "dorp",
  "dorpen",
  "naam",
  "namen",
  "de vliegveld",
  "faculteit",
  "de faculteit van geneeskunde",
  "de faculteit van engineering",
  "de faculteit van handel",
  "de faculteit van de islamitische wetgeving",
  "christen",
  "christenen",
  "de profeet",
  "de religie",
  "moge Allah hem genezen",
  "Caïro",
  "de week",
  "de les",
  "de toets",
  "broer",
  "broers",
  "Griekenland",
  "Meisje",
  "kleinzoon",
  "de rechtbank",
  "de gebedsrichting",
  "de grondwet",
  "de rivier",
  "de zee",
  "het hotel",
  "het vliegtuig",
  "de directeur van het bedrijf",
  "Japans",
  "het bedrijf",
  "goedkoop",
  "bloezen",
  "schrijfbord",
  "Riyaal",
  "wijk",
  "gebedseenheid",
  "elke",
  "elke van hun",
  "elke van jullie",
  "elke van ons",
  "land",
  "verschillend",
  "bus",
  "van hen",
  "Europa",
  "Joegoslavië",
  "bedankt",
  "de dag",
  "dagen",
  "de prijs",
  "helft",
  "gebedseenheden",
  "wiel",
  "het feest",
  "het jaar",
  "raam",
  "liniaal",
  "Rood",
  "Blauw",
  "Groen",
  "Zwart",
  "Geel",
  "Wit",
  "minuut",
  "minuten",
  "sleutels",
  "hij zei",
  "zij zei",
  "oud (mv)",
  "passagiers",
  "passagier",
  "de kom",
  "de kommen",
  "doekjes",
  "De hotels",
];

//Function to generate random numbers. Will be used for indexes.
function generateNum() {
  //generate a random number
  return (num = Math.floor(Math.random() * arabicWords.length));
}

//Saving elements as variables
let arabicWord = document.getElementById("arabic-word");
let userAnswer = document.getElementById("user-answer");
let result = document.getElementById("result");
let question = document.getElementById("question");
let startGame = document.getElementById("start-game");
let nextQuestion = document.getElementById("next-question");
let correct = document.getElementById("correct");
let incorrect = document.getElementById("incorrect");

//Generate random index
let randIndex = generateNum();

function playGame() {
  //Clear input field because user might have played before
  userAnswer.value = ""; //Clear input field after each question

  //Game will be called via a button in the HTML file
  arabicWord.innerHTML = arabicWords[randIndex]; //Display a random Arabic Word

  //Show the elements needed to play the game
  question.style.display = "block";
  userAnswer.style.display = "block";
  nextQuestion.style.display = "block";

  //Hide the start game button since the game is started already
  startGame.style.display = "none";
}

function next() {
  //This functions compares answers, output result and loads the next question
  let currentUserAnswer = userAnswer.value.toLowerCase(); //Save current user's answer
  correctAnswer = dutchWords[randIndex].toLowerCase(); //Save correct answer

  //Check if answer is correct
  if (currentUserAnswer === correctAnswer) {
    correct.style.display = "block";
    incorrect.style.display = "none";
  } else {
    correct.style.display = "none";
    incorrect.style.display = "block";
  }

  //Output the question, user's answer and correct answer
  result.innerHTML = `
  <ul>
  <li>Vorige vraag: <span class="thick big-word">${arabicWords[randIndex]}</span></li>
  <li>Je antwoord: <span class ="thick">${currentUserAnswer}</span></li>
  <li>Juiste antwoord: <span class="thick">${correctAnswer}</span></li>
  </ul>
  `;

  randIndex = generateNum(); //Generate another random index after each question
  userAnswer.value = ""; //Clear input field after each question
  arabicWord.innerHTML = arabicWords[randIndex]; //Display next question
}
